import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebars Configuration for Docusaurus Documentation
 *
 * This configuration enables you to:
 * - Automatically generate a sidebar based on the folder structure.
 * - Manually define a custom sidebar structure if needed.
 * 
 * You can switch between autogenerated and manual sidebars based on your requirements.
 */

const sidebars: SidebarsConfig = {
  /**
   * Autogenerated Sidebar:
   * Automatically generates a sidebar from the file structure in the "docs" directory.
   * Useful for projects with a straightforward or hierarchical content layout.
   */
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  /**
   * Example Manual Sidebar (Commented):
   * Uncomment the following section if you'd like to define a sidebar manually.
   */
  /*
  tutorialSidebar: [
    // Single document reference
    'intro',
    'hello',
    // Category with nested items
    {
      type: 'category',
      label: 'Tutorial',
      collapsible: true,
      collapsed: false,
      items: ['tutorial-basics/create-a-document', 'tutorial-basics/deploy-your-site'],
    },
    // External link example
    {
      type: 'link',
      label: 'Docusaurus Docs', // Link label
      href: 'https://docusaurus.io', // URL
    },
  ],
  */
};

export default sidebars;
